spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: wangyang
    url: jdbc:mysql://localhost:3306/db1?useSSL=false
  main:
    banner-mode: off
server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
    banner: false
